:: # Copyright 2013, Big Switch Networks, Inc.
:: # Copyright 2018, Red Hat, Inc.
:: #
:: # LoxiGen is licensed under the Eclipse Public License, version 1.0 (EPL), with
:: # the following special exception:
:: #
:: # LOXI Exception
:: #
:: # As a special exception to the terms of the EPL, you may distribute libraries
:: # generated by LoxiGen (LoxiGen Libraries) under the terms of your choice, provided
:: # that copyright and licensing notices generated by LoxiGen are not altered or removed
:: # from the LoxiGen Libraries and the notice provided below is (i) included in
:: # the LoxiGen Libraries, if distributed in source code form and (ii) included in any
:: # documentation for the LoxiGen Libraries, if distributed in binary form.
:: #
:: # Notice: "Copyright 2013, Big Switch Networks, Inc. This library was generated by the LoxiGen Compiler."
:: #
:: # You may not use this file except in compliance with the EPL or LOXI Exception. You may obtain
:: # a copy of the EPL at:
:: #
:: # http://www.eclipse.org/legal/epl-v10.html
:: #
:: # Unless required by applicable law or agreed to in writing, software
:: # distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
:: # WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
:: # EPL for the specific language governing permissions and limitations
:: # under the EPL.

package ${package}

import "github.com/google/gopacket"

type MessageType uint8
type PortNo uint16
type FmCmd uint16
type FlowWildcards uint32
type uint128_t struct {
	hi uint64
	lo uint64
}
type Checksum128 [16]byte
type Serializable interface {
	SerializeTo(b gopacket.SerializeBuffer, opts gopacket.SerializeOptions) error
	DecodeFromBytes(data []byte, df gopacket.DecodeFeedback) error
}
type Match = MatchV1

// TODO: set real types
type WcBmap uint32
type BSNVport uint32

func (c *Checksum128) Decode([]byte) error {
	return nil
}

func (c *Checksum128) Serialize([]byte) error {
	return nil
}

func (c *PortNo) Decode([]byte) error {
	return nil
}

func (c *PortNo) Serialize([]byte) error {
	return nil
}